# Generated by Django 6.1.1 on 2026-10-05 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
