name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Забрать код
        uses: actions/checkout@v4

      - name: Установить Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Установить зависимости
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Проверить настройки Django
        run: python manage.py check

      - name: Применить миграции
        run: python manage.py migrate

      - name: Запустить тесты
        run: python manage.py test

